name: Fix pnpm-lock after renovate

on:
  push:
    branches:
      - 'renovate/*'
    paths:
      - 'pnpm-lock.yaml'

jobs:
  fix-lock:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Fix & comment
        run: |
          corepack pnpm i --no-frozen-lockfile
          node bin/cdxgen.js -t js
          read -a array <<< "${{ github.event.head_commit.message }}"
          echo "Output of \`pnpm why ${array[github.event.head_commit.message.contains('dependency') ? 3 : 2]}\`:" > _tree.txt
          echo "\`\`\`" >> _tree.txt
          corepack pnpm why ${array[github.event.head_commit.message.contains('dependency') ? 3 : 2]} >> _tree.txt
          echo "\`\`\`" >> _tree.txt
          echo "Output of \`grep\`:"
          echo "\`\`\`" >> _tree.txt
          grep -nA20 ${array[github.event.head_commit.message.contains('dependency') ? 3 : 2]} bom.json >> _tree.txt
          echo "\`\`\`" >> _tree.txt
        env:
          CDXGEN_DEBUG_MODE: debug
      - uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          message-path: _tree.txt
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: 'pnpm-lock.yaml'
          commit: --signoff
          default_author: github_actions
          message: Fixed pnpm-lock after renovate update
