name: Fix pnpm-lock after renovate

on:
  pull_request:
    branches:
      - 'renovate/*'
    paths:
      - 'pnpm-lock.yaml'
  push:
    branches:
      - 'renovate/*'
    paths:
      - 'pnpm-lock.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fix-lock:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: PNPM install
        run: |
          corepack pnpm i --no-frozen-lockfile
      - name: PNPM why
        if: ${{ startsWith(github.event.head_commit.message, 'chore(deps):') }}
        run: |
          read -a array <<< "${{ github.event.head_commit.message }}"
          echo "Ouput of \`pnpm why ${array[3]}\`:" > _why.txt
          echo "\`\`\`" >> _why.txt
          corepack pnpm why ${array[3]} >> _why.txt
          echo "\`\`\`" >> _why.txt
      - uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        if: ${{ startsWith(github.event.head_commit.message, 'chore(deps):') }}
        with:
          message-path: _why.txt
      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: 'pnpm-lock.yaml'
          commit: --signoff
          default_author: github_actions
          message: Fixed pnpm-lock after renovate update
