name: nydus tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  build:
    if: github.repository == 'CycloneDX/cdxgen'
    strategy:
      fail-fast: false
      matrix:
        java-version: ['24']
        node-version: ['24.7.0']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          repository: 'DependencyTrack/dependency-track'
          path: 'repotests/dependency-track'
      - name: setup nydus
        run: |
          curl -LO https://github.com/dragonflyoss/nydus/releases/download/v2.3.1/nydus-static-v2.3.1-linux-amd64.tgz
          tar -xvf nydus-static-v2.3.1-linux-amd64.tgz
          chmod +x nydus-static/*
          mv nydus-static/* /usr/local/bin/
          rm -rf nydus-static-v2.3.1-linux-amd64.tgz nydus-static
          curl -LO https://github.com/containerd/nerdctl/releases/download/v2.0.3/nerdctl-full-2.0.3-linux-amd64.tar.gz
          sudo tar Cxzvf /usr/local nerdctl-full-2.0.3-linux-amd64.tar.gz
          sudo mkdir -p /etc/nydus/
          sudo rm -rf /var/lib/containerd-nydus
          curl -LO https://github.com/containerd/nydus-snapshotter/releases/download/v0.15.0/nydus-snapshotter-v0.15.0-x86_64.tgz
          sudo tar Cxzvf /usr/local/bin nydus-snapshotter-v0.15.0-x86_64.tgz
          sudo mv /usr/local/bin/nydus-snapshotter/* /usr/local/bin/
          sudo cp ./ci/nydusd-config.fusedev.json /etc/nydus/nydusd-config.fusedev.json
          sudo mkdir -p /etc/containerd
          sudo cp ./ci/containerd-config.toml /etc/containerd/config.toml
          sudo systemctl enable --now containerd
          sudo systemctl restart containerd
      - name: compile
        run: |
          cd repotests/dependency-track
          mvn -q clean compile -DskipTests -Dmaven.test.skip=true
      - name: nydustests
        run: |
          sudo /usr/local/bin/containerd-nydus-grpc --nydusd-config /etc/nydus/nydusd-config.fusedev.json &
          sleep 15
          cd repotests/dependency-track
          sudo nerdctl --snapshotter nydus run --rm -e JAVA_TOOL_OPTIONS -v $HOME/.m2:$HOME/.m2 -v $(pwd):/app ghcr.io/cyclonedx/cdxgen:master-nydus --deep -t java /app -o /app/bom.json
          ls -ltr
        env:
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
      - name: cleanup
        run: |
          cd repotests/dependency-track
          rm bom.json
          sudo rm -rf /var/lib/containerd-nydus
        continue-on-error: true
      - name: dockertests
        run: |
          sleep 15
          cd repotests/dependency-track
          sudo nerdctl run --rm -e JAVA_TOOL_OPTIONS -v $HOME/.m2:$HOME/.m2 -v $(pwd):/app ghcr.io/cyclonedx/cdxgen:master --deep -t java /app -o /app/bom.json
          ls -ltr
        env:
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
